name: flutter_lab9
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Для збереження даних (TODO 2 / локальний сторедж)
  shared_preferences: ^2.2.2

  # ДОДАНО: Для мережевих запитів та Mock-тестів (TODO 9)
  http: ^1.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Для мокування сервісів та API
  mockito: ^5.4.4
  build_runner: ^2.4.8

  # Для чистоти коду
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true